### ISSUE TITLE
Link opens in a separate tab but the script doesn't really right-click on it

### ISSUE THREAD

**Issue by eabedrapo** [cjohnsonjava/TAU-Selenium-WebDriver-Java#1]
Although the goal of opening the link in a separate tab is accomplished, you aren't doing so via right-click that opens the contextual menu.

So I think you should change the JavaDoc comment in line 31 to explain the code opens the link in a separate tab.
https://github.com/cjohnsonjava/TAU-Selenium-WebDriver-Java/blob/470915f8aad68a6177e3bf7261cb877362d1823f/src/main/java/pages/DynamicLoadingPage.java#L31

Also, the method signature should be renamed to be consistent with the actual result of its excecution
https://github.com/cjohnsonjava/TAU-Selenium-WebDriver-Java/blob/470915f8aad68a6177e3bf7261cb877362d1823f/src/main/java/pages/DynamicLoadingPage.java#L33

**Comment by cjohnsonjava** [comment]
Thanks for the feedback. I updated the comment to reflect that it opens a new tab by holding the left Ctrl key and clicking on the mouse.
