### ISSUE TITLE
Repeated code to switch windows

### ISSUE THREAD

**Issue by eabedrapo** [cjohnsonjava/TAU-Selenium-WebDriver-Java#2]
I think you should modify your code to call the switchToWindow() method from switchToTab() to avoid repeating the same for loop.
https://github.com/cjohnsonjava/TAU-Selenium-WebDriver-Java/blob/470915f8aad68a6177e3bf7261cb877362d1823f/src/main/java/utils/WindowManager.java#L48

**Comment by cjohnsonjava** [comment]
Thanks for the feedback.
